### ISSUE TITLE
raw table content

### ISSUE THREAD

**Issue by ericxin1982** [iRon7/ConvertFrom-SourceTable#6]
Hi @iRon7 

the source table content, I am curious how you generated, I just thought want to generate and save them in file, and when I need it, I would get-content from file and use it by convertfrom-sourcetable.

But I do not know, need help.

PS C:\> $Colors = ConvertFrom-SourceTable '
	Name       Value         RGB
	----       -----         ---
	Black   0x000000       0,0,0
	White   0xFFFFFF 255,255,255
	Red     0xFF0000     255,0,0
	Lime    0x00FF00     0,255,0
	Blue    0x0000FF     0,0,255
	Yellow  0xFFFF00   255,255,0
	Cyan    0x00FFFF   0,255,255
	Magenta 0xFF00FF   255,0,255
	Silver  0xC0C0C0 192,192,192
	Gray    0x808080 128,128,128
	Maroon  0x800000     128,0,0
	Olive   0x808000   128,128,0
	Green   0x008000     0,128,0
	Purple  0x800080   128,0,128
	Teal    0x008080   0,128,128
	Navy    0x000080     0,0,128
'

**Comment by iRon7** [comment]
There is actually (afaik) no standard way to create a table as the example you refer to. Generally, you could us the `Format-Table` cmdlet to create a "SourceTable" where right aligned values (usually primitives) are evaluated as arrays (like the ones in the example) will also be intepretted. It is just that if an (external) command would output an array in a column it would probably look like this.
Generally, this cmdlet is meant to restore data that is output from an extrenal command (or an inadvisable `Format-Table` usage) or from an easy readable embedded table in a script (which -for now- sometimes needs to be created/modified manually).

**Comment by ericxin1982** [comment]
Thanks so much!
